env: "dev"
grpc:
  port: 44044
storage:
  path: "/home/hellokitty/GolandProjects/cloud/images/cloud/" # path to storage folder
cloud:
  max_image_size: 20971520 # 20Mb
  available_ext:
    ".jpg":
    ".jpeg":
    ".png":
    ".webp":
  limit_ud: 10 # download/upload limit
  limit_list: 100 # list limit
